spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/qaqat/IdeaProjects/SpringGuides/demo/todo-db'
    password: ''
    username: 'sa'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    enable:
      http: false
keycloak:
  auth-server-url: 'http://localhost:8180'
  realm: 'ToDoApp'
  resource: 'todo-spring-client'
  public-client: true