spring:
  profiles:
    active: local
  jpa:
    hibernate.ddl-auto: validate
  main:
    banner-mode: off
server:
  error:
    include-message: always
task.template.allowMultipleTasks: false
management:
  endpoints:
    web:
      base-path: '/base'
